### ISSUE TITLE
wrong paper link

### ISSUE THREAD

**Issue by kwea123** [autonomousvision/mip-splatting#1]
it links to monosdf

**Comment by michaelrubloff** [comment]
Following! Having the same issue!

**Comment by niujinshuchong** [comment]
Hi, thanks for the reminder. We use it as a placeholder. Fixed now. The paper can be found here: https://drive.google.com/file/d/1Q7KgGbynzcIEyFJV1I17HgrYz6xrOwRJ/view?usp=sharing
