### ISSUE TITLE
Unable to reproduce your results

### ISSUE THREAD

**Issue by Contrail97** [autonomousvision/mip-splatting#10]
![Weixin Screenshot_20231209113302](https://github.com/autonomousvision/mip-splatting/assets/28862680/c184c7f5-25fe-426f-934d-35d53cbfd309)
![Weixin Screenshot_20231209113330](https://github.com/autonomousvision/mip-splatting/assets/28862680/f80449b8-87ff-4de7-b72b-55ad460c392a)
There is my command and I didn't change anything from your code: python ./scripts/run_mipnerf360.py ,
but I uploaded the .ply generated by your code to the onlineviwer I found some floaters and white spots.

**Comment by Contrail97** [comment]
Those results all exhibited in iteration_30000

**Comment by niujinshuchong** [comment]
Hi, the viewer expects fused point cloud as input. Please follow here for how to create it. https://github.com/autonomousvision/mip-splatting#online-viewer

**Comment by Ericgone** [comment]
> ![Weixin Screenshot_20231209113302](https://private-user-images.githubusercontent.com/28862680/289230842-c184c7f5-25fe-426f-934d-35d53cbfd309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODg2MTksIm5iZiI6MTcxMDk4ODMxOSwicGF0aCI6Ii8yODg2MjY4MC8yODkyMzA4NDItYzE4NGM3ZjUtMjVmZS00MjZmLTkzNGQtMzVkNTNjYmZkMzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAyMzE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMWY5OGRjOTZiMDQ1ZDgwNjY5OWE5ZTQ4YzI2YjY4NjVjYmU1Nzk3YjY5OGUwZTIzOTU0MzdhZjk3NTk3NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tlSyVI5I8HWFaLRGtki5vhVn1j4OtZfWP_7ULPBPT14) ![Weixin Screenshot_20231209113330](https://private-user-images.githubusercontent.com/28862680/289230846-f80449b8-87ff-4de7-b72b-55ad460c392a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODg2MTksIm5iZiI6MTcxMDk4ODMxOSwicGF0aCI6Ii8yODg2MjY4MC8yODkyMzA4NDYtZjgwNDQ5YjgtODdmZi00ZGU3LWI3MmItNTVhZDQ2MGMzOTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAyMzE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYTEyZWNiYWNjM2FkM2NlZGJhOTQ4MWZiN2MxMzFkYTA4NGQ4NWM5Zjk5ODMzOGUwMmU5MmVhNmM5Nzc1ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5R7zg1LMv9rU2TcmUbEmRgv7lqivu0oOsVQktqE-MJA) There is my command and I didn't change anything from your code: python ./scripts/run_mipnerf360.py , but I uploaded the .ply generated by your code to the onlineviwer I found some floaters and white spots.

Hi， do we need to run"create_fused_ply,py" to obtain all metric values?
