### ISSUE TITLE
the meaning of "Mip-Splatting w/o 2D Mip filter"

### ISSUE THREAD

**Issue by Yang-Xijie** [autonomousvision/mip-splatting#13]
Hi, thanks for your great work!

I have a question about the part "8. Ablation": To evaluate the effectiveness of the 2D Mip filter, you show Table 5/6/7. And these three tables all have a row with the title "Mip-Splatting w/o 2D Mip filter".

I am confused about the "w/o 2D Mip filter" -- do you just remove the 2D Mip filter, or remove the 2D Mip filter and re-add the Dilation operator? That is to say, I wonder whether "Mip-Splatting w/o 2D Mip filter" means "3DGS + 3D smoothing filter" or "3DGS - Dilation + 3D smoothing filter".

---

From the part "8.1 Effectiveness of the 3D Smoothing Filter", you mention that "The absence of both the 3D smoothing filter and the 2D Mip filter leads to an excessive generation of small Gaussian primitives". So "removing both the 3D smoothing filter and the 2D Mip filter" means "3DGS - Dilation" (compare Table 5 and Table 6). So I guess that "Mip-Splatting w/o 2D Mip filter" means "3DGS - Dilation + 3D smoothing filter"?

**Comment by niujinshuchong** [comment]
Yes, it is. You can simply set `--kernel_size 0.0` for "ours w/o 2D Mip filter".
