### ISSUE TITLE
about 5.1 3D Smoothing Filter 

### ISSUE THREAD

**Issue by garrisonz** [autonomousvision/mip-splatting#14]
Thanks your great work!

One question:
In the last paragraph in `5.1 3D Smoothing Filter`, 
"By employing 3D Gaussian smoothing, we ensure that the highest frequency component of any Gaussian does not exceed half of its maximal sampling rate for at least one camera."

As I know, gaussian filter is soft smoothing filter, so most high frequency ($> \hat v_k/2$) component of a gaussian will be remove, but still very little high frequency ($> \hat v_k/2$) component will remain .
Am I corret?

In one word:
No any high frequency($> \hat v_k/2$) component remain, or still very little high frequency($> \hat v_k/2$)  component remain?

**Comment by niujinshuchong** [comment]
Hi, you are correct. Gaussian filter is not an ideal low-pass filter so it can't filter high-frequency components completely. Will change the description to make it more clear. Thanks for the correction.

**Comment by garrisonz** [comment]
Thank you!
