### ISSUE TITLE
about eq. (9)

### ISSUE THREAD

**Issue by garrisonz** [autonomousvision/mip-splatting#15]
Thanks your great work again!

In `gaussian_model.py`, fiter_3D = distance / focal_length * scale1
according paper eq. (9), new gaussian covariance matrix's scale should be  $\sqrt{scale^2 + filter3D}$
But, why in function `get_scaling_with_3D_filter()` is $\sqrt{scale^2 + filter3D^2}$ ?
Why square fiter_3D? Thanks

**Comment by niujinshuchong** [comment]
Hi, there is a typo in eq. 9, where v_k should be v_k ^2 in eq. 9. Will update it in the revised paper. Thanks for pointing it out.
