### ISSUE TITLE
About Eq.9 

### ISSUE THREAD

**Issue by wunianguiguolu** [autonomousvision/mip-splatting#19]
In Eq.9, it is the square of covariance plus the square of 3D Filter, but in the code, it is the square of exp(scaling) plus the square of 3D Filter squared. Why?
<img width="376" alt="3DGS-MIP-2" src="https://github.com/autonomousvision/mip-splatting/assets/93069822/12c9f293-7dfb-4bd2-aa72-c47df2efa994">
<img width="521" alt="3DGS-MIP-1" src="https://github.com/autonomousvision/mip-splatting/assets/93069822/8d8c67d2-7c89-4190-a3de-96f3da6a9fa1">

**Comment by wunianguiguolu** [comment]
![Uploading image.png…]()

**Comment by wunianguiguolu** [comment]
<img width="717" alt="image" src="https://github.com/autonomousvision/mip-splatting/assets/93069822/bf110cf6-a57c-48e6-8d4b-eb1f9a6a80aa">

**Comment by wunianguiguolu** [comment]
<img width="358" alt="image" src="https://github.com/autonomousvision/mip-splatting/assets/93069822/47f987c6-8432-43e6-8a39-497b6e4fc38e">

**Comment by wunianguiguolu** [comment]
From the ablation study, I think it is 2D Mip filter solves dilation, not 3D Smooth filter, which is different from the conclution from the games 310
<img width="719" alt="image" src="https://github.com/autonomousvision/mip-splatting/assets/93069822/130cbeb5-e44a-4b45-a071-efd7497293e2">

**Comment by wunianguiguolu** [comment]
<img width="814" alt="image" src="https://github.com/autonomousvision/mip-splatting/assets/93069822/e9ceeeca-8967-4bed-a38e-c7a16fbaa9ea">
<img width="724" alt="image" src="https://github.com/autonomousvision/mip-splatting/assets/93069822/281a9360-4968-47e8-a196-def912609f92">
And how about dilation(zooming out)?

**Comment by Yang-Xijie** [comment]
> I think 3D Smooth filter solve high frequency artifacts by limiting the smallest scale of gaussian (zooming in) and 2D Mip filter solve dilation and aliasing (zooming out).

From my own point of view,

- 3D filter prevents small gaussians in a scene, which mainly solves high frequency artifacts.
- 3D filter and 2D filter both solve aliasing because they lower the frequency of the scene (pre-filtering).
- The fix for coefficient of gaussian filter in EWA splatting solves dilation (check https://github.com/graphdeco-inria/gaussian-splatting/issues/294#issuecomment-1772688093 for detail), which is included in the 2D filter in this paper.

**Comment by wunianguiguolu** [comment]
I agree with your first and second statement. However, for dilation, I think the reason for the artifacts caused by dilation is too small gaussian(too high frequency) for zooming out.

**Comment by wunianguiguolu** [comment]
The coefficient of gaussian filter in EWA splatting is a good correction but not contribute for solving dilation.(I think)

**Comment by Harvey-Mei** [comment]
> Hi, we first get the original scale of the Gaussian by `self.get_scaling` and after applying square it becomes the variances (left term in L105). Then we apply the 3D filter (sum in L105 in your screenshot, eq.9 in the paper). Finally applying sqrt to the variance results in scales after 3D filtering.

Hi, I have some doubts about the variance here.
 
In the definition of variacne in 3D GS, it contains the rotation.
<img width="752" alt="Image" src="https://github.com/user-attachments/assets/494f5220-c014-415c-96ae-0d3d25f56ab2" />



![Image](https://github.com/user-attachments/assets/ae3c5648-fdbf-444b-b64d-92834c797880)

But in the code, it seems that only the scale part was considered. I understand that the function of a 3D filter is to control the scale, so it is correct to have an effect on the scale. If we understand it this way, then it seems that the variance addition part in formula 9 does not match。
<img width="467" alt="Image" src="https://github.com/user-attachments/assets/0b189b9a-c8e3-43ef-b7ca-528240f08ac1" />
