### ISSUE TITLE
Would the online viewer be open-source?

### ISSUE THREAD

**Issue by KovenYu** [autonomousvision/mip-splatting#21]
Hi, thanks for great work.

Just wonder if the online viewer would also be open-source?

Thanks.

**Comment by niujinshuchong** [comment]
Hi, the viewer is modified from https://github.com/mkkellogg/GaussianSplats3D.

**Comment by hecodeit** [comment]
> You can find the modified version for mip-splatting here: https://github.com/niujinshuchong/niujinshuchong.github.io/tree/master/mip-splatting-demo

Hello! @niujinshuchong
Although the link provided points to the location of the Viewer's JavaScript source code, there are two issues that need to be addressed:
1. The source code is packaged, and it is unclear which parts of GaussianSplats3D have been modified;
2. The online viewer for mip-splatting has performance issues. For the same scene, such as Garden, the frame rate for mip-splatting is only 30 FPS, while the online demo for GaussianSplats3D achieves 60 FPS. How can the rendering performance of mip-splatting be improved?
