### ISSUE TITLE
About eq.9 and eq.10

### ISSUE THREAD

**Issue by immortalmin** [autonomousvision/mip-splatting#23]
Shouldn't the coefficient of Gaussian on the left side of equation (9) be 1? Instead of normalized Gaussian. 
<img width="758" alt="image" src="https://github.com/autonomousvision/mip-splatting/assets/42803282/3eee963c-3941-446d-a474-79f74dc0e144">
Equation (10) is also.
<img width="707" alt="image" src="https://github.com/autonomousvision/mip-splatting/assets/42803282/ee51f89d-3499-4dae-bcca-b1396c705272">

**Comment by niujinshuchong** [comment]
Hi, the coef of a Gaussian before normalization is 1 and after applying the filter there will be a coef <= 1.
