### ISSUE TITLE
Multi resolution training

### ISSUE THREAD

**Issue by KeKsBoTer** [autonomousvision/mip-splatting#24]
Hey, 

Thanks for publishing your code! 
In the paper, you write that you train and test on multi-resolution images (40% full resolution).
In the code this is activated with the "sample_more_highres" flag. 
But this flag is only set to True for the synthetic data.
Am I missing something or do you not sample different resolutions for the other datasets?

Thank you!

**Comment by niujinshuchong** [comment]
Hi, Yes, we have multi-resolution training only on the NeRF-synthetic dataset. For other experiments on the paper (single-scale training and testing on mip-nerf 360 dataset and single-scale training multi-scale testing on both NeRF-synthetic and mip-nerf 360 dataset), we only use a single scale images, so it is not used.

**Comment by KeKsBoTer** [comment]
Thank you for the quick reply!
