### ISSUE TITLE
Thanks for your great work. Does the s in equation (9) refer to 0.2 in the code?

### ISSUE THREAD

**Issue by qhdqhd** [autonomousvision/mip-splatting#27]
Does the s in equation (9) refer to 0.2 in the code?
![PVE1EH_OPFVCC`51@32G7ZK](https://github.com/autonomousvision/mip-splatting/assets/42370719/2aa50c4a-d54b-4e5e-a36d-66e9868d683d)
![E4D67C9 5VDBKWKDSLJXBON](https://github.com/autonomousvision/mip-splatting/assets/42370719/cca78cd9-0a46-4228-adfd-f27db704f563)

**Comment by qhdqhd** [comment]
Thanks for your fast response.
I just can not understand why is ` opacity * coef `?  I thought it should be ` scale * coef ` to make the scale of the 3d gaussian ball larger.

`    def get_opacity_with_3D_filter(self):
        opacity = self.opacity_activation(self._opacity)
        # apply 3D filter
        scales = self.get_scaling
        
        scales_square = torch.square(scales)
        det1 = scales_square.prod(dim=1)
        
        scales_after_square = scales_square + torch.square(self.filter_3D) 
        det2 = scales_after_square.prod(dim=1) 
        coef = torch.sqrt(det1 / det2)
        return opacity * coef[..., None]`

**Comment by niujinshuchong** [comment]
Hi, scale is modified in get_scale_with_3D_filter. Here the coef is the sqrt part in your screenshot.
