### ISSUE TITLE
OMP_NUM_THREADS not recognised

### ISSUE THREAD

**Issue by JackySlo** [autonomousvision/mip-splatting#28]
As I am trying to Train the model, I get the issue stating OMP_NUM_THREADS not recognised as an internal or external command..., 
Any clue what I could be doing wrong?
I am pretty new to this subject, so any help would be appreciated.
Thanks

**Comment by niujinshuchong** [comment]
Hi, you can delete it in the running script. It's just for our cluster.

**Comment by JackySlo** [comment]
Right, thank you very much.
