### ISSUE TITLE
about the meaning of kernel_size

### ISSUE THREAD

**Issue by pansanity666** [autonomousvision/mip-splatting#32]
Hi, 

Thanks for your great work!
A stupid question is that what exactly does kernel_size in the code mean, and why it is set as 0.1 for all the exps?

Best,

**Comment by niujinshuchong** [comment]
Hi, the kernel size controls the the size of our 2D mip filter and it is choose to approximate a single pixel (box filter). The following figure shows Gaussians with different kernel sizes (0.1, 0.3, and 1.0) and a box filter that we want to approximate. Using kernel size = 0.1 approximates the box filter well. 
![Screenshot from 2024-04-18 09-47-01](https://github.com/autonomousvision/mip-splatting/assets/13434986/a07bab71-9df1-4248-bb53-9ef2162671cd)

**Comment by pansanity666** [comment]
Thanks for your clear explanation!
