### ISSUE TITLE
About GPU Memory

### ISSUE THREAD

**Issue by KeKer7** [autonomousvision/mip-splatting#36]
Thank you for your awesome work! In the bicycle scene that is downsampled 4 times, at 3000 iterations, the 3090 24G memory is full and the training is slow. It seems that mip-splatting requires much more densified point clouds than the original 3DGS.  What is the GPU memory overhead of the scene?

**Comment by niujinshuchong** [comment]
Hi, more points are allocated in the latest code with densification metric in our Gaussian opacity fields paper, which improve the results at the cost of using more points. You can fall back to the https://github.com/autonomousvision/mip-splatting/tree/1ecf7d53d6e131a192ac1deb5acda26b5b252946 to test the original mip-splatting. Or simply use a large threshold here https://github.com/autonomousvision/mip-splatting/blob/main/train.py#L163 such as 0.05 and 0.5 to remove more points.

**Comment by KeKer7** [comment]
thank you for your reply！
