### ISSUE TITLE
can not display in the viewer which provided by graphdeco-inria

### ISSUE THREAD

**Issue by Linkersem** [autonomousvision/mip-splatting#4]
Hi, greate work,, but it  seems can not display in the viewer which provided by graphdeco-inria?

**Comment by Eric-chuan** [comment]
you need modify the diff-gaussian-rasterization in SIBR too.

**Comment by Linkersem** [comment]
Emm，aright, could you give me some guide to modify th diff-gaussian-rasterization? thx for your kind

**Comment by Vreqn** [comment]
I'm also be intrigued on how we'd need to modify the SIBR viewer to display the MIP Splats

**Comment by Octweiyi** [comment]
the api has already been changed, simply modify the diff-gaussian-rasterization cannot work.

**Comment by Eric-chuan** [comment]
> the api has already been changed, simply modify the diff-gaussian-rasterization cannot work. Could you update the SIBR of your version? Thx a lot.api

the data structure of gaussian has been modified. So the loadPly func in `GaussianView.cpp` should be modify. And the `get_opacity_with_3D_filter` and `get_scaling_with_3D_filter` should also re-implement.

**Comment by shadoking** [comment]
> > the api has already been changed, simply modify the diff-gaussian-rasterization cannot work. Could you update the SIBR of your version? Thx a lot.api
> 
> the data structure of gaussian has been modified. So the loadPly func in `GaussianView.cpp` should be modify. And the `get_opacity_with_3D_filter` and `get_scaling_with_3D_filter` should also re-implement.

Can you please provide more details or update the code related to SIBR directly？

**Comment by niujinshuchong** [comment]
Hi, you can also refer to here https://github.com/autonomousvision/mip-splatting/pull/9.
