### ISSUE TITLE
How to use custom data for training

### ISSUE THREAD

**Issue by cici19850** [autonomousvision/mip-splatting#45]
What should I do if I want to use custom data for training。
Looking forward to your reply, thank you

**Comment by landax-223** [comment]
I already try it success.You just need to do the same with the origin 3D gauss splatting.

**Comment by cici19850** [comment]
> I already try it success.You just need to do the same with the origin 3D gauss splatting.

I saw in the code that the camera mode must be PINHOLE or SIMPLE.PINHOLE. Do I need to process it into these two modes during data preprocessing?Can data captured by smartphones also be processed using these two camera modes?

**Comment by landax-223** [comment]
I have tried to use the video taken by my smartphone for the original 3D GS.You try converted it into sparse/camera.bin, images.bin,point3D.bin. I also try change .txt model.it not work.The camera mode inside is not pinhole.

**Comment by cici19850** [comment]
> I have tried to use the video taken by my smartphone for the original 3D GS.You try converted it into sparse/camera.bin, images.bin,point3D.bin. I also try change .txt model.it not work.The camera mode inside is not pinhole.

Thank you
