### ISSUE TITLE
The low-pass filter in Eq. 8 and Eq. 9

### ISSUE THREAD

**Issue by DapengFeng** [autonomousvision/mip-splatting#5]
Thank you for your work! I have a question about the low-pass filter in Eq. 8 and Eq.9, i.e., how do you construct it?

**Comment by zf-666** [comment]
Same question, looking at the paper it should be limiting cov3d based on depth and f during computation, but I can't find the  related code.

**Comment by niujinshuchong** [comment]
The 3D filter can be found here: https://github.com/autonomousvision/mip-splatting/blob/main/scene/gaussian_model.py#L126-L137 and the 2D filter is here: https://github.com/autonomousvision/mip-splatting/blob/main/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu#L111-L123

**Comment by SYSUykLin** [comment]
> The 3D filter can be found here: https://github.com/autonomousvision/mip-splatting/blob/main/scene/gaussian_model.py#L126-L137 and the 2D filter is here: https://github.com/autonomousvision/mip-splatting/blob/main/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu#L111-L123

And the eq7, did u omit the gaussian which outside the camera frustum？ I did not find the code in in_frustum of the anxiliary.h file.

**Comment by niujinshuchong** [comment]
Hi, the in_frustum code is here: https://github.com/autonomousvision/mip-splatting/blob/main/scene/gaussian_model.py#L175
