### ISSUE TITLE
Can't train with my own dataset

### ISSUE THREAD

**Issue by TacoAndCheese** [autonomousvision/mip-splatting#50]
I try to train with my own dataset, but when I train it got this error. Any help for this?
![3d](https://github.com/user-attachments/assets/130604fe-6a25-4440-ad73-d2762492fdee)

**Comment by niujinshuchong** [comment]
Hi, you need to install the rasterisation following readme.

**Comment by TacoAndCheese** [comment]
Lol, I thought I install at beginning looks like I miss ed it haha. 
Thanks for that
