### ISSUE TITLE
Does it support RealityCapture

### ISSUE THREAD

**Issue by cici19850** [autonomousvision/mip-splatting#51]
Does it support RealityCapture？Can I use the point cloud data processed by RealityCapture for training？

**Comment by niujinshuchong** [comment]
Hi, Yes. But you need to change the data loader to read the point cloud and camera poses from RealityCapture.

**Comment by cici19850** [comment]
> Hi, Yes. But you need to change the data loader to read the point cloud and camera poses from RealityCapture.

How should I  loader to read the point cloud and camera poses from RealityCapture?
Do I need to modify the source code? Or what are the cmd parameters?

**Comment by niujinshuchong** [comment]
You need to add your own code to load the point cloud and poses.
