### ISSUE TITLE
Is there a clerical error in readme.md

### ISSUE THREAD

**Issue by biter0088** [autonomousvision/mip-splatting#52]
May I ask the author if the word “single” in the `readme.md` file is a clerical error and should be written as “multi”? The location is as shown in the picture below.
![2024-10-10_22-46](https://github.com/user-attachments/assets/7c28f53f-5677-4e06-92b5-05f769cd47b8)

**Comment by niujinshuchong** [comment]
Yes, it is a typo. Fixed. Thanks.
