### ISSUE TITLE
Mip-Splatting (ours) w/o 3D smoothing filter

### ISSUE THREAD

**Issue by luocha0107** [autonomousvision/mip-splatting#57]
Hi,a nice job.
I would like to do ablation experiments on Mip-Splatting (ours) w/o 3D smoothing filter,what should i do?
Is there direct command-line code available?
I directly set filter_3D to 0, but training to 10% shows cuda kernel error.

**Comment by niujinshuchong** [comment]
Hi, I think we simply change this line https://github.com/autonomousvision/mip-splatting/blob/main/scene/gaussian_model.py#L190 to `filter_3D = distance / focal_length * 0.0`.

**Comment by luocha0107** [comment]
> Hi, I think we simply change this line https://github.com/autonomousvision/mip-splatting/blob/main/scene/gaussian_model.py#L190 to `filter_3D = distance / focal_length * 0.0`.
ok,i get it! thank you for reply.
