### ISSUE TITLE
Error: nvrtc: error: invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by chensh1127** [autonomousvision/mip-splatting#7]
hey, you did a great job. I encountered an error during the deployment of the project, which led to **unsuccessful training** and **Unable to compute metrics** for model. Can you please help me identify the reason for this?

the error is 
nvrtc: error: invalid value for --gpu-architecture (-arch)
Training progress:   0%|                                                                                                                        | 0/30000 [00:00<?, ?it/s]
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]

best wishes,

**Comment by niujinshuchong** [comment]
Hope it is resolved.

**Comment by chensh1127** [comment]
thank you very much. it is solved

**Comment by evyy1234** [comment]
> thank you very much. it is solved

could you tell me how to solve it? thanks a lot
